name: Build HTML version

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Jupyter
        run: pip install jupyterlab sparqlkernel

      - name: Install zazuko kernel
        run: python -m ipykernel install --user --name=zazuko

      - name: Install SPARQL kernel
        run: jupyter sparqlkernel install --user zazuko

      - name: Build HTML version of the notebook
        run: ./run.sh

      - name: Configure CNAME
        run: echo jupyter.zazuko.com > html/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: html
