name: Build HTML version

on:
  push:
    branches:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: poetry install

      - name: Install Jupyter
        run: pip install jupyterlab sparqlkernel

      - name: Install zazuko kernel
        run: python -m ipykernel install --user --name=zazuko

      - name: Install SPARQL kernel
        run: jupyter sparqlkernel install --user zazuko

      - name: Build HTML version of the notebook
        run: ./run.sh

      # Only deploy on GitHub Pages if we are on the "master" branch
      - name: Configure CNAME
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: echo jupyter.zazuko.com > html/CNAME

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: html
